name: Release

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build Project
        run: ./gradlew build --stacktrace -x test

  publish:
    needs: build
    runs-on: ubuntu-latest

    env:
      KORDEX_USER: ${{ secrets.NEXUS_USER }}
      KORDEX_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
      GPG_SIGNING_PASS: ${{ secrets.GPG_SIGNING_PASS }}
      GITHUB_BRANCH_NAME: ${{ github.ref }}
      GITHUB_TAG_NAME: ${{ github.event.release.tag_name }}
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4

        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Publish Project
        run: ./gradlew publishAndReleaseToMavenCentral -x test
