name: Release

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Artifacts
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: build --stacktrace -x test
          gradle-home-cache-cleanup: true

  publish:
    needs: build
    runs-on: ubuntu-latest

    env:
      NEXUS_USER: ${{ secrets.NEXUS_USER }}
      NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
      GPG_SIGNING_PASS: ${{ secrets.GPG_SIGNING_PASS }}
      GITHUB_BRANCH_NAME: ${{ github.ref }}
      GITHUB_TAG_NAME: ${{ github.event.release.tag_name }}
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Publish with Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: publish -x test
          gradle-home-cache-cleanup: true
